source "https://rubygems.org"

gem "rack", "3.1.13"
gem "nokogiri", "1.18.8", :require => false

group :development do
  gem "rspec", "3.13.0"
end

source "https://rails-assets.org" do
  gem "rails-assets-jquery", "3.7.1"
end
